apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.app.replicas | default 1 }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      containers:
        - name: "{{ .Values.app.name }}"
          image: {{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "{{ .Values.app.resources.limits.memory }}"
              cpu: "{{ .Values.app.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: SPRING_PROFILES
              value: {{ .Values.app.profile }}
            - name: MYSQL_DB_HOST
              value: {{ .Values.db.name }}-svc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: dbusername
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secret.name }}"
                  key: dbpassword
      imagePullSecrets:
        - name: regcred
